/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  people: [
    {
      type: 'category',
      label: '教师',
      items: [
        'people/advisor/index',
      ],
    },
    {
      type: 'category',
      label: '合作教师',
      items: [
        'people/co-advisor/yiboxue',
        'people/co-advisor/zhenchen',
        'people/co-advisor/jinzhou',
        'people/co-advisor/chenglongli',
      ]
    },
    {
      type: 'category',
      label: '博士后',
      items: [
        'people/postdoc/yihangluo',
        'people/postdoc/yangxiang',
        'people/postdoc/kaiwang',
        'people/postdoc/zhenlongyuan',
        'people/postdoc/xiaohehu',
      ]
    },
    {
      type: 'category',
      label: '在校学生',
      items: [
        'people/student/xiwang',
        'people/student/jiancui',
        'people/student/yilv',
        'people/student/mingfeng',
      ]
    },
    {
      type: 'category',
      label: '毕业学生',
      items: [
        'people/student/jinzhou',
        'people/student/kaili',
        'people/student/quanhuang',
        'people/student/shengke',
        'people/student/weirong',
        'people/student/jianming',
        'people/student/weiwang',
        'people/student/yinchen',
        'people/student/feili',
        'people/student/xinzhou',
        'people/student/guanghua',
        'people/student/zongwei',
        'people/student/yuankun',
        'people/student/kanghong',
        'people/student/shimeng',
        'people/student/yihan',
        'people/student/fachao',
        'people/student/lianghong',
        'people/student/yinhuai',
        'people/student/guangyu',
        'people/student/yiyao',
        'people/student/yingzhang',
        'people/student/litang',
        'people/student/boxu',
        'people/student/huizhang',
        'people/student/guodong',
        'people/student/rongxiao',
        'people/student/yaxuan',
        'people/student/zhiming',
        'people/student/feihe',
        'people/student/jiandu',
        'people/student/xinming',
        'people/student/Jeffrey',
        'people/student/jinli',
        'people/student/lingyun',
        'people/student/beipeng',
        'people/student/fanxiang',
        'people/student/luli',
        'people/student/yangwu',
        'people/student/jingjie',
        'people/student/xiaoqi',
        'people/student/qingxu',
        'people/student/baohua',
        'people/student/yanggao',
        'people/student/jiaji',
        'people/student/chengliu',
        'people/student/xiwei',
        'people/student/chenchen',
        'people/student/changchen',
        'people/student/kaiwang',
        'people/student/xiangwang',
        'people/student/fengxie',
        'people/student/changchen-calvin',
        'people/student/wenxun',
        'people/student/yuanjun',
        'people/student/dongyu',
        'people/student/zhenlong',
        'people/student/changsheng',
        'people/student/jiaqi',
        'people/student/yiyang',
        'people/student/shijie',
        'people/student/hangzhu',
        'people/student/linli',
        'people/student/zhiliu',
        'people/student/nanzhou',
        'people/student/danyang',
        'people/student/junyang',
        'people/student/zhefu',
        'people/student/jiazheng',
        'people/student/shuowang',
        'people/student/yunpeng',
        'people/student/Mohammad',
        'people/student/xiaohe',
        'people/student/qinglv',
        'people/student/fangqi',
        'people/student/changchang',
        'people/student/Didier',
        'people/student/juxing',
        'people/student/jiafu',
        'people/student/chengjun',
        'people/student/yifan',
      ]
    },
  ],
  research: [
    'research/index',
    'research/pm',
    'research/tm',
    'research/pe',
    'research/si',
    'research/on',
    'research/ts',
  ],
  share: [
    'share/index',
    'share/pm',
    'share/tm',
    'share/pe',
    'share/si',
    'share/other',
    'share/on',
    'share/survey',
  ],
};
